include $(APPDIR)/Make.defs

PROGNAME  = camera_bridge
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_DEFAULT_TASK_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_CAMERA_BRIDGE)

MAINSRC   = camera_bridge_main.c

include $(APPDIR)/Application.mk
